# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-12 10:52
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Length has to be 10', regex='^\\d{10}$')])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField(verbose_name='Teacher Age')),
                ('picture', models.ImageField(blank=True, default='teacher/img/default.png', height_field='height_field', null=True, upload_to='', verbose_name='profile picture', width_field='width_field')),
                ('height_field', models.IntegerField(default=600, null=True)),
                ('width_field', models.IntegerField(default=600, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
