# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='height_field',
            field=models.IntegerField(default=600, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='width_field',
            field=models.IntegerField(default=600, null=True),
        ),
    ]
