# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170909_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='institute_name',
            new_name='school',
        ),
    ]
