# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-12 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
